apiVersion: v1
kind: ConfigMap
metadata:
  name: dokpotok-config
  namespace: dokpotok
data:
  IRIS_LOG_LEVEL: "INFO"
  DATABASE_URL: "postgresql+asyncpg://user:pass@postgres:5432/iris"
  REDIS_URL: "redis://redis:6379/0"
