apiVersion: v1
kind: Secret
metadata:
  name: dokpotok-secrets
  namespace: dokpotok
type: Opaque
stringData:
  SECRET_KEY: "<base64-encoded>"
  OPENAI_API_KEY: "<base64-encoded>"
  POSTGRES_USER: "<base64-encoded>"
  POSTGRES_PASSWORD: "<base64-encoded>"
  POSTGRES_DB: "<base64-encoded>"
