[pytest]
pythonpath = .
markers =
    api: API tests
    ui: UI tests
    architecture: architecture checks
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20