import type {
  Department,
  Employee,
  BpmnNode,
  BpmnEdge,
  Problem,
  DepartmentKey,
} from './types';

export const OE = 50;   // ширина полосы отдела
export const GS = 1200; // ширина зоны диаграммы
export const BD = 650;  // высота диаграммы

export const DEPARTMENTS: Department[] = [
  {
    key: 'sales',
    label: 'Отдел продаж / Тендеры',
    shortLabel: 'ПРОДАЖИ',
    color: '#ea6c2b',
    bg: '#fff7f3',
    border: '#f5d0b8',
    employees: ['emp1', 'emp2'],
    laneY: 0,
    laneH: 130,
  },
  {
    key: 'design',
    label: 'Проектирование / КБ',
    shortLabel: 'ПРОЕКТИРОВАНИЕ',
    color: '#1a6fc4',
    bg: '#f0f6ff',
    border: '#b8d4f5',
    employees: ['emp3', 'emp4', 'emp5'],
    laneY: 130,
    laneH: 130,
  },
  {
    key: 'supply',
    label: 'Отдел снабжения / МТО',
    shortLabel: 'СНАБЖЕНИЕ',
    color: '#2e8a52',
    bg: '#f0faf4',
    border: '#b0dfc0',
    employees: ['emp6', 'emp7'],
    laneY: 260,
    laneH: 130,
  },
  {
    key: 'assembly',
    label: 'Производство / Сборка',
    shortLabel: 'ПРОИЗВОДСТВО',
    color: '#6b3fa0',
    bg: '#f6f0ff',
    border: '#d0b8f5',
    employees: ['emp8', 'emp9', 'emp10', 'emp11'],
    laneY: 390,
    laneH: 130,
  },
  {
    key: 'shipping',
    label: 'Отгрузка / ОТК',
    shortLabel: 'ОТГРУЗКА',
    color: '#c47a1a',
    bg: '#fffaf0',
    border: '#f5ddb8',
    employees: ['emp12', 'emp13'],
    laneY: 520,
    laneH: 130,
  },
];

export const DEPARTMENT_BY_KEY: Record<DepartmentKey, Department> = DEPARTMENTS.reduce(
  (acc, d) => ({ ...acc, [d.key]: d }),
  {} as Record<DepartmentKey, Department>
);

export const EMPLOYEES: Employee[] = [
  {
    id: 'emp1',
    name: 'Волков А.С.',
    role: 'Менеджер по тендерам',
    dept: 'sales',
    kpiLoad: 85,
    tasks: ['task_tender', 'task_contract'],
  },
  {
    id: 'emp2',
    name: 'Морозова Е.В.',
    role: 'Коммерческий директор',
    dept: 'sales',
    kpiLoad: 72,
    tasks: ['task_contract', 'task_kickoff'],
  },
  {
    id: 'emp3',
    name: 'Ильин Д.М.',
    role: 'Главный инженер-проектировщик',
    dept: 'design',
    kpiLoad: 94,
    tasks: ['task_tz', 'task_spec', 'task_schema'],
  },
  {
    id: 'emp4',
    name: 'Петрова О.Л.',
    role: 'Инженер КИПиА',
    dept: 'design',
    kpiLoad: 78,
    tasks: ['task_schema', 'task_bom'],
  },
  {
    id: 'emp5',
    name: 'Савельев К.Р.',
    role: 'Конструктор',
    dept: 'design',
    kpiLoad: 88,
    tasks: ['task_bom', 'task_spec'],
  },
  {
    id: 'emp6',
    name: 'Харитонов В.И.',
    role: 'Начальник снабжения',
    dept: 'supply',
    kpiLoad: 91,
    tasks: ['task_purchase', 'task_incoming'],
  },
  {
    id: 'emp7',
    name: 'Зайцева Н.П.',
    role: 'Менеджер по закупкам',
    dept: 'supply',
    kpiLoad: 79,
    tasks: ['task_purchase'],
  },
  {
    id: 'emp8',
    name: 'Кузнецов П.А.',
    role: 'Мастер цеха',
    dept: 'assembly',
    kpiLoad: 83,
    tasks: ['task_montage', 'task_wiring'],
  },
  {
    id: 'emp9',
    name: 'Семёнов Е.Н.',
    role: 'Монтажник ЩУ',
    dept: 'assembly',
    kpiLoad: 76,
    tasks: ['task_montage'],
  },
  {
    id: 'emp10',
    name: 'Громов В.С.',
    role: 'Электромонтажник',
    dept: 'assembly',
    kpiLoad: 80,
    tasks: ['task_wiring'],
  },
  {
    id: 'emp11',
    name: 'Тарасова А.К.',
    role: 'Наладчик / тестировщик',
    dept: 'assembly',
    kpiLoad: 89,
    tasks: ['task_test'],
  },
  {
    id: 'emp12',
    name: 'Фёдоров С.М.',
    role: 'Начальник ОТК',
    dept: 'shipping',
    kpiLoad: 67,
    tasks: ['task_otk', 'task_shipping'],
  },
  {
    id: 'emp13',
    name: 'Никулина Т.В.',
    role: 'Логист / документовед',
    dept: 'shipping',
    kpiLoad: 73,
    tasks: ['task_shipping'],
  },
];

const LX = OE; // левая граница зоны диаграммы

export const BPMN_NODES: BpmnNode[] = [
  {
    id: 'start',
    label: 'Старт',
    dept: 'sales',
    x: LX + 20,
    y: 50,
    w: 36,
    h: 36,
    type: 'event',
    issue: 'ok',
    docs: [],
    employees: [],
    kpis: [],
    description: 'Начало процесса: поступление тендерной документации или запроса от клиента.',
    avgDays: 0,
  },
  {
    id: 'task_tender',
    label: 'Участие в тендере',
    dept: 'sales',
    x: LX + 80,
    y: 28,
    w: 170,
    h: 76,
    type: 'task',
    issue: 'bottleneck',
    docs: ['Тендерная документация', 'КП (коммерческое предложение)', 'Технические требования заказчика'],
    employees: ['emp1'],
    kpis: [
      { label: 'Выигранные тендеры', value: '34%', status: 'warn' },
      { label: 'Время подготовки КП', value: '4.2 дня', status: 'warn' },
      { label: 'Кол-во тендеров/мес', value: '8–12', status: 'ok' },
    ],
    description: 'Анализ тендерной документации, подготовка КП, согласование технических требований. Узкое место: один менеджер на все тендеры.',
    avgDays: 5,
  },
  {
    id: 'gw_tender',
    label: 'Тендер выигран?',
    dept: 'sales',
    x: LX + 360,
    y: 43,
    w: 46,
    h: 46,
    type: 'gateway',
    issue: 'ok',
    docs: [],
    employees: [],
    kpis: [],
    description: 'Шлюз принятия решения: тендер выигран — переход к договору; нет — архив.',
    avgDays: 0,
  },
  {
    id: 'task_contract',
    label: 'Заключение договора',
    dept: 'sales',
    x: LX + 440,
    y: 28,
    w: 180,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Договор поставки', 'Технический паспорт на ЩУ', 'Протокол согласования цены'],
    employees: ['emp1', 'emp2'],
    kpis: [
      { label: 'Срок подписания', value: '≤ 7 дней', status: 'ok' },
      { label: 'Доля аванса', value: '30–50%', status: 'ok' },
    ],
    description: 'Согласование и подписание договора с клиентом. Фиксируются сроки, стоимость, технические требования.',
    avgDays: 7,
  },
  {
    id: 'task_kickoff',
    label: 'Kick-off совещание',
    dept: 'sales',
    x: LX + 680,
    y: 28,
    w: 170,
    h: 76,
    type: 'task',
    issue: 'duplicate',
    docs: ['Протокол совещания', 'Реестр требований'],
    employees: ['emp2'],
    kpis: [
      { label: 'Участники', value: '3–5 чел.', status: 'ok' },
      { label: 'Длительность', value: '1–2 ч', status: 'ok' },
    ],
    description: 'Передача проекта в КБ. Дублирует часть передачи ТЗ — возможна оптимизация через единый формуляр.',
    avgDays: 1,
  },
  {
    id: 'task_tz',
    label: 'Разработка ТЗ',
    dept: 'design',
    x: LX + 80,
    y: 158,
    w: 150,
    h: 76,
    type: 'task',
    issue: 'bottleneck',
    docs: ['Техническое задание (ТЗ)', 'Опросный лист заказчика', 'Нормы ПУЭ / ГОСТ'],
    employees: ['emp3'],
    kpis: [
      { label: 'Срок разработки ТЗ', value: '3–5 дней', status: 'warn' },
      { label: 'Кол-во итераций', value: '2.1 ср.', status: 'warn' },
      { label: 'Загрузка инженера', value: '94%', status: 'crit' },
    ],
    description: 'Разработка технического задания на ЩУ. Критический ресурс: один главный инженер. Узкое место процесса.',
    avgDays: 5,
  },
  {
    id: 'task_schema',
    label: 'Электрические схемы',
    dept: 'design',
    x: LX + 320,
    y: 158,
    w: 160,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Принципиальная схема Э3', 'Схема подключения', 'Перечень элементов'],
    employees: ['emp3', 'emp4'],
    kpis: [
      { label: 'Срок разработки', value: '4–7 дней', status: 'ok' },
      { label: 'Ошибки в ревизии', value: '1.3 ср.', status: 'ok' },
    ],
    description: 'Разработка принципиальных электрических схем, схем подключений, перечней элементов в CAD-системе.',
    avgDays: 6,
  },
  {
    id: 'task_spec',
    label: 'Спецификация оборудования',
    dept: 'design',
    x: LX + 540,
    y: 158,
    w: 170,
    h: 76,
    type: 'task',
    issue: 'duplicate',
    docs: ['Спецификация на оборудование (Ф3)', 'BOM-лист', 'Ведомость покупных изделий'],
    employees: ['emp4', 'emp5'],
    kpis: [
      { label: 'Точность BOM', value: '91%', status: 'warn' },
      { label: 'Срок согласования', value: '2–3 дня', status: 'ok' },
    ],
    description: 'Формирование спецификации оборудования. Дублирование: BOM-лист формируется и в дизайне, и в снабжении — рекомендуется единая система.',
    avgDays: 3,
  },
  {
    id: 'task_bom',
    label: 'Согласование BOM со снабжением',
    dept: 'design',
    x: LX + 780,
    y: 158,
    w: 190,
    h: 76,
    type: 'task',
    issue: 'bottleneck',
    docs: ['Согласованная спецификация', 'Протокол замены позиций'],
    employees: ['emp5', 'emp6'],
    kpis: [
      { label: 'Число замен позиций', value: '18% поз.', status: 'warn' },
      { label: 'Время согласования', value: '2–4 дня', status: 'warn' },
    ],
    description: 'Согласование BOM со снабжением на предмет наличия и стоимости. Частые замены позиций создают задержки.',
    avgDays: 3,
  },
  {
    id: 'task_purchase',
    label: 'Закупка материалов и оборудования',
    dept: 'supply',
    x: LX + 320,
    y: 288,
    w: 200,
    h: 76,
    type: 'task',
    issue: 'bottleneck',
    docs: ['Заявки на закупку', 'Счета поставщиков', 'Договоры поставки', 'Товарные накладные'],
    employees: ['emp6', 'emp7'],
    kpis: [
      { label: 'Срок поставки (ср.)', value: '18 дней', status: 'crit' },
      { label: 'Дефицит позиций', value: '12%', status: 'warn' },
      { label: 'Соотв. бюджету', value: '88%', status: 'warn' },
    ],
    description: 'Закупка оборудования, кабелей, крепежа, корпусов. Главное узкое место: длинные сроки поставки зарубежного оборудования.',
    avgDays: 18,
  },
  {
    id: 'task_incoming',
    label: 'Входной контроль ТМЦ',
    dept: 'supply',
    x: LX + 570,
    y: 288,
    w: 160,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Акт входного контроля', 'Сертификаты соответствия', 'Упаковочные листы'],
    employees: ['emp6'],
    kpis: [
      { label: '% брака при поставке', value: '3.2%', status: 'ok' },
      { label: 'Срок контроля', value: '1–2 дня', status: 'ok' },
    ],
    description: 'Входной контроль качества и комплектности поступающих материальных ценностей. Документирование актами.',
    avgDays: 2,
  },
  {
    id: 'task_warehouse',
    label: 'Склад / выдача на сборку',
    dept: 'supply',
    x: LX + 800,
    y: 288,
    w: 170,
    h: 76,
    type: 'task',
    issue: 'duplicate',
    docs: ['Требование-накладная М-11', 'Карточка складского учёта'],
    employees: ['emp6'],
    kpis: [
      { label: 'Точность комплектации', value: '96%', status: 'ok' },
      { label: 'Время выдачи', value: '0.5 дня', status: 'ok' },
    ],
    description: 'Хранение и выдача материалов в производство. Дублирование учёта: в 1С и в Excel-таблицах склада.',
    avgDays: 1,
  },
  {
    id: 'task_montage',
    label: 'Монтаж оборудования в корпус',
    dept: 'assembly',
    x: LX + 320,
    y: 418,
    w: 180,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Технологическая карта', 'Схема размещения оборудования', 'Инструкции производителей'],
    employees: ['emp8', 'emp9'],
    kpis: [
      { label: 'Выработка (шк./мес)', value: '4–6 ед.', status: 'ok' },
      { label: 'Отклонение от плана', value: '±2 дня', status: 'ok' },
    ],
    description: 'Механический монтаж оборудования, автоматов, реле, DIN-рейки в корпус шкафа согласно схеме размещения.',
    avgDays: 4,
  },
  {
    id: 'task_wiring',
    label: 'Электромонтаж / кабельные работы',
    dept: 'assembly',
    x: LX + 570,
    y: 418,
    w: 180,
    h: 76,
    type: 'task',
    issue: 'bottleneck',
    docs: ['Схема Э3', 'Кабельный журнал', 'Маркировочные листы'],
    employees: ['emp8', 'emp10'],
    kpis: [
      { label: 'Трудоёмкость (ч/ед.)', value: '32 ч', status: 'warn' },
      { label: 'Ошибки разводки', value: '2.4/ед.', status: 'warn' },
      { label: 'Переделки', value: '15%', status: 'warn' },
    ],
    description: 'Прокладка кабелей, подключение по схемам. Узкое место: высокая трудоёмкость и ошибки из-за неактуальных схем.',
    avgDays: 5,
  },
  {
    id: 'task_test',
    label: 'Наладка и испытания',
    dept: 'assembly',
    x: LX + 820,
    y: 418,
    w: 150,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Программа и методика испытаний', 'Протокол испытаний', 'Паспорт изделия'],
    employees: ['emp11'],
    kpis: [
      { label: 'Процент с первого предъявления', value: '78%', status: 'warn' },
      { label: 'Среднее время наладки', value: '1.5 дня', status: 'ok' },
    ],
    description: 'Функциональные испытания шкафа, проверка автоматики, настройка параметров защит и управления.',
    avgDays: 3,
  },
  {
    id: 'task_otk',
    label: 'Контроль ОТК',
    dept: 'shipping',
    x: LX + 570,
    y: 548,
    w: 140,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Акт приёмки ОТК', 'Ведомость замечаний', 'Паспорт изделия'],
    employees: ['emp12'],
    kpis: [
      { label: '% изделий с замечаниями', value: '22%', status: 'warn' },
      { label: 'Срок устранения', value: '1–3 дня', status: 'ok' },
    ],
    description: 'Финальный технический контроль качества готового изделия по требованиям договора и ГОСТам.',
    avgDays: 2,
  },
  {
    id: 'task_shipping',
    label: 'Упаковка и отгрузка',
    dept: 'shipping',
    x: LX + 800,
    y: 548,
    w: 170,
    h: 76,
    type: 'task',
    issue: 'ok',
    docs: ['Товарная накладная (ТОРГ-12)', 'Упаковочный лист', 'Акт сдачи-приёмки', 'Инструкция по монтажу'],
    employees: ['emp12', 'emp13'],
    kpis: [
      { label: 'Своевременность отгрузки', value: '81%', status: 'warn' },
      { label: 'Рекламации', value: '4.1%', status: 'ok' },
    ],
    description: 'Упаковка изделия, оформление отгрузочных документов, передача заказчику или транспортной компании.',
    avgDays: 2,
  },
  {
    id: 'end',
    label: 'Завершено',
    dept: 'shipping',
    x: LX + 1040,
    y: 568,
    w: 36,
    h: 36,
    type: 'event',
    issue: 'ok',
    docs: [],
    employees: [],
    kpis: [],
    description: 'Проект завершён. Шкаф управления передан заказчику.',
    avgDays: 0,
  },
];

export const BPMN_EDGES: BpmnEdge[] = [
  { id: 'f1', from: 'start', to: 'task_tender', type: 'sequence' },
  { id: 'f2', from: 'task_tender', to: 'gw_tender', type: 'sequence' },
  { id: 'f3', from: 'gw_tender', to: 'task_contract', label: 'Да', type: 'conditional' },
  { id: 'f4', from: 'task_contract', to: 'task_kickoff', type: 'sequence' },
  { id: 'f5', from: 'task_kickoff', to: 'task_tz', type: 'message' },
  { id: 'f6', from: 'task_tz', to: 'task_schema', type: 'sequence' },
  { id: 'f7', from: 'task_schema', to: 'task_spec', type: 'sequence' },
  { id: 'f8', from: 'task_spec', to: 'task_bom', type: 'sequence' },
  { id: 'f9', from: 'task_bom', to: 'task_purchase', type: 'message' },
  { id: 'f10', from: 'task_purchase', to: 'task_incoming', type: 'sequence' },
  { id: 'f11', from: 'task_incoming', to: 'task_warehouse', type: 'sequence' },
  { id: 'f12', from: 'task_warehouse', to: 'task_montage', type: 'message' },
  { id: 'f13', from: 'task_bom', to: 'task_montage', type: 'message' },
  { id: 'f14', from: 'task_montage', to: 'task_wiring', type: 'sequence' },
  { id: 'f15', from: 'task_wiring', to: 'task_test', type: 'sequence' },
  { id: 'f16', from: 'task_test', to: 'task_otk', type: 'message' },
  { id: 'f17', from: 'task_otk', to: 'task_shipping', type: 'sequence' },
  { id: 'f18', from: 'task_shipping', to: 'end', type: 'sequence' },
];

export const PROBLEMS: Problem[] = [
  {
    id: 'bn1',
    title: 'Перегруз главного инженера',
    severity: 'crit',
    tasks: ['task_tz'],
    description: 'Ильин Д.М. — единственный разработчик ТЗ (загрузка 94%). Задержка в ТЗ блокирует всю цепочку: схемы → BOM → закупки → сборку.',
    recommendation: 'Передать часть задач Савельеву К.Р. или нанять 2-го инженера-конструктора.',
  },
  {
    id: 'bn2',
    title: 'Длинный срок поставки ТМЦ',
    severity: 'crit',
    tasks: ['task_purchase'],
    description: 'Среднее время поставки — 18 дней, в т.ч. из-за зарубежных компонентов. Дефицит позиций: 12%.',
    recommendation: 'Ввести предварительное резервирование под типовые проекты, расширить базу локальных поставщиков.',
  },
  {
    id: 'bn3',
    title: 'Высокая трудоёмкость электромонтажа',
    severity: 'warn',
    tasks: ['task_wiring'],
    description: '32 ч/ед. с 15% переделок из-за расхождений между схемами и BOM. Ошибки 2.4 на изделие.',
    recommendation: 'Внедрить PLM-систему для управления версиями схем; добавить цифровые маркировочные листы.',
  },
  {
    id: 'bn4',
    title: 'Дублирование BOM в дизайне и снабжении',
    severity: 'warn',
    tasks: ['task_spec', 'task_warehouse'],
    description: 'BOM-лист формируется в КБ (Excel) и параллельно ведётся в 1С снабжением. Расхождения приводят к ошибкам закупки.',
    recommendation: 'Перейти на единую PDM/PLM систему (например, Lotsman или Teamcenter) как источник истины для BOM.',
  },
  {
    id: 'bn5',
    title: 'Низкий % с первого предъявления ОТК',
    severity: 'warn',
    tasks: ['task_test', 'task_otk'],
    description: '78% изделий сдаются с первого предъявления ОТК. 22% возвращаются на доработку, задерживая отгрузку.',
    recommendation: 'Внедрить промежуточный контроль после электромонтажа, ввести чек-лист самоконтроля монтажника.',
  },
];
