"""Базовый набор данных производственного процесса (для seed при пустых таблицах).

Значения KPI, которые являются измеренной статистикой (проценты, средние),
оставлены пустыми: реальные данные появятся позже и подставятся через API
(PATCH /production/nodes/{id}, PATCH /production/employees/{id}).
Нормативные значения (сроки, плановые диапазоны) сохранены.
"""

LX = 50  # левая граница зоны диаграммы (OE)

DEPARTMENTS = [
    dict(key="sales", label="Отдел продаж / Тендеры", short_label="ПРОДАЖИ",
         color="#ea6c2b", bg="#fff7f3", border="#f5d0b8", lane_y=0, lane_h=130, position=0),
    dict(key="design", label="Проектирование / КБ", short_label="ПРОЕКТИРОВАНИЕ",
         color="#1a6fc4", bg="#f0f6ff", border="#b8d4f5", lane_y=130, lane_h=130, position=1),
    dict(key="supply", label="Отдел снабжения / МТО", short_label="СНАБЖЕНИЕ",
         color="#2e8a52", bg="#f0faf4", border="#b0dfc0", lane_y=260, lane_h=130, position=2),
    dict(key="assembly", label="Производство / Сборка", short_label="ПРОИЗВОДСТВО",
         color="#6b3fa0", bg="#f6f0ff", border="#d0b8f5", lane_y=390, lane_h=130, position=3),
    dict(key="shipping", label="Отгрузка / ОТК", short_label="ОТГРУЗКА",
         color="#c47a1a", bg="#fffaf0", border="#f5ddb8", lane_y=520, lane_h=130, position=4),
]

EMPLOYEES = [
    dict(id="emp1", name="Волков А.С.", role="Менеджер по тендерам", dept_key="sales",
         kpi_load=0, tasks=["task_tender", "task_contract"], position=0),
    dict(id="emp2", name="Морозова Е.В.", role="Коммерческий директор", dept_key="sales",
         kpi_load=0, tasks=["task_contract", "task_kickoff"], position=1),
    dict(id="emp3", name="Ильин Д.М.", role="Главный инженер-проектировщик", dept_key="design",
         kpi_load=0, tasks=["task_tz", "task_spec", "task_schema"], position=2),
    dict(id="emp4", name="Петрова О.Л.", role="Инженер КИПиА", dept_key="design",
         kpi_load=0, tasks=["task_schema", "task_bom"], position=3),
    dict(id="emp5", name="Савельев К.Р.", role="Конструктор", dept_key="design",
         kpi_load=0, tasks=["task_bom", "task_spec"], position=4),
    dict(id="emp6", name="Харитонов В.И.", role="Начальник снабжения", dept_key="supply",
         kpi_load=0, tasks=["task_purchase", "task_incoming"], position=5),
    dict(id="emp7", name="Зайцева Н.П.", role="Менеджер по закупкам", dept_key="supply",
         kpi_load=0, tasks=["task_purchase"], position=6),
    dict(id="emp8", name="Кузнецов П.А.", role="Мастер цеха", dept_key="assembly",
         kpi_load=0, tasks=["task_montage", "task_wiring"], position=7),
    dict(id="emp9", name="Семёнов Е.Н.", role="Монтажник ЩУ", dept_key="assembly",
         kpi_load=0, tasks=["task_montage"], position=8),
    dict(id="emp10", name="Громов В.С.", role="Электромонтажник", dept_key="assembly",
         kpi_load=0, tasks=["task_wiring"], position=9),
    dict(id="emp11", name="Тарасова А.К.", role="Наладчик / тестировщик", dept_key="assembly",
         kpi_load=0, tasks=["task_test"], position=10),
    dict(id="emp12", name="Фёдоров С.М.", role="Начальник ОТК", dept_key="shipping",
         kpi_load=0, tasks=["task_otk", "task_shipping"], position=11),
    dict(id="emp13", name="Никулина Т.В.", role="Логист / документовед", dept_key="shipping",
         kpi_load=0, tasks=["task_shipping"], position=12),
]

NODES = [
    dict(id="start", label="Старт", dept_key="sales", x=LX + 20, y=50, w=36, h=36,
         type="event", issue="ok", docs=[], employees=[], kpis=[],
         description="Начало процесса: поступление тендерной документации или запроса от клиента.",
         avg_days=0, position=0),
    dict(id="task_tender", label="Участие в тендере", dept_key="sales", x=LX + 80, y=28, w=170, h=76,
         type="task", issue="bottleneck",
         docs=["Тендерная документация", "КП (коммерческое предложение)", "Технические требования заказчика"],
         employees=["emp1"],
         kpis=[
             {"label": "Выигранные тендеры", "value": "", "status": "warn"},
             {"label": "Время подготовки КП", "value": "", "status": "warn"},
             {"label": "Кол-во тендеров/мес", "value": "", "status": "ok"},
         ],
         description="Анализ тендерной документации, подготовка КП, согласование технических требований. Узкое место: один менеджер на все тендеры.",
         avg_days=5, position=1),
    dict(id="gw_tender", label="Тендер выигран?", dept_key="sales", x=LX + 360, y=43, w=46, h=46,
         type="gateway", issue="ok", docs=[], employees=[], kpis=[],
         description="Шлюз принятия решения: тендер выигран — переход к договору; нет — архив.",
         avg_days=0, position=2),
    dict(id="task_contract", label="Заключение договора", dept_key="sales", x=LX + 440, y=28, w=180, h=76,
         type="task", issue="ok",
         docs=["Договор поставки", "Технический паспорт на ЩУ", "Протокол согласования цены"],
         employees=["emp1", "emp2"],
         kpis=[
             {"label": "Срок подписания", "value": "≤ 7 дней", "status": "ok"},
             {"label": "Доля аванса", "value": "30–50%", "status": "ok"},
         ],
         description="Согласование и подписание договора с клиентом. Фиксируются сроки, стоимость, технические требования.",
         avg_days=7, position=3),
    dict(id="task_kickoff", label="Kick-off совещание", dept_key="sales", x=LX + 680, y=28, w=170, h=76,
         type="task", issue="duplicate",
         docs=["Протокол совещания", "Реестр требований"],
         employees=["emp2"],
         kpis=[
             {"label": "Участники", "value": "3–5 чел.", "status": "ok"},
             {"label": "Длительность", "value": "1–2 ч", "status": "ok"},
         ],
         description="Передача проекта в КБ. Дублирует часть передачи ТЗ — возможна оптимизация через единый формуляр.",
         avg_days=1, position=4),
    dict(id="task_tz", label="Разработка ТЗ", dept_key="design", x=LX + 80, y=158, w=150, h=76,
         type="task", issue="bottleneck",
         docs=["Техническое задание (ТЗ)", "Опросный лист заказчика", "Нормы ПУЭ / ГОСТ"],
         employees=["emp3"],
         kpis=[
             {"label": "Срок разработки ТЗ", "value": "3–5 дней", "status": "warn"},
             {"label": "Кол-во итераций", "value": "", "status": "warn"},
             {"label": "Загрузка инженера", "value": "", "status": "crit"},
         ],
         description="Разработка технического задания на ЩУ. Критический ресурс: один главный инженер. Узкое место процесса.",
         avg_days=5, position=5),
    dict(id="task_schema", label="Электрические схемы", dept_key="design", x=LX + 320, y=158, w=160, h=76,
         type="task", issue="ok",
         docs=["Принципиальная схема Э3", "Схема подключения", "Перечень элементов"],
         employees=["emp3", "emp4"],
         kpis=[
             {"label": "Срок разработки", "value": "4–7 дней", "status": "ok"},
             {"label": "Ошибки в ревизии", "value": "", "status": "ok"},
         ],
         description="Разработка принципиальных электрических схем, схем подключений, перечней элементов в CAD-системе.",
         avg_days=6, position=6),
    dict(id="task_spec", label="Спецификация оборудования", dept_key="design", x=LX + 540, y=158, w=170, h=76,
         type="task", issue="duplicate",
         docs=["Спецификация на оборудование (Ф3)", "BOM-лист", "Ведомость покупных изделий"],
         employees=["emp4", "emp5"],
         kpis=[
             {"label": "Точность BOM", "value": "", "status": "warn"},
             {"label": "Срок согласования", "value": "2–3 дня", "status": "ok"},
         ],
         description="Формирование спецификации оборудования. Дублирование: BOM-лист формируется и в дизайне, и в снабжении — рекомендуется единая система.",
         avg_days=3, position=7),
    dict(id="task_bom", label="Согласование BOM со снабжением", dept_key="design", x=LX + 780, y=158, w=190, h=76,
         type="task", issue="bottleneck",
         docs=["Согласованная спецификация", "Протокол замены позиций"],
         employees=["emp5", "emp6"],
         kpis=[
             {"label": "Число замен позиций", "value": "", "status": "warn"},
             {"label": "Время согласования", "value": "2–4 дня", "status": "warn"},
         ],
         description="Согласование BOM со снабжением на предмет наличия и стоимости. Частые замены позиций создают задержки.",
         avg_days=3, position=8),
    dict(id="task_purchase", label="Закупка материалов и оборудования", dept_key="supply", x=LX + 320, y=288, w=200, h=76,
         type="task", issue="bottleneck",
         docs=["Заявки на закупку", "Счета поставщиков", "Договоры поставки", "Товарные накладные"],
         employees=["emp6", "emp7"],
         kpis=[
             {"label": "Срок поставки (ср.)", "value": "", "status": "crit"},
             {"label": "Дефицит позиций", "value": "", "status": "warn"},
             {"label": "Соотв. бюджету", "value": "", "status": "warn"},
         ],
         description="Закупка оборудования, кабелей, крепежа, корпусов. Главное узкое место: длинные сроки поставки зарубежного оборудования.",
         avg_days=18, position=9),
    dict(id="task_incoming", label="Входной контроль ТМЦ", dept_key="supply", x=LX + 570, y=288, w=160, h=76,
         type="task", issue="ok",
         docs=["Акт входного контроля", "Сертификаты соответствия", "Упаковочные листы"],
         employees=["emp6"],
         kpis=[
             {"label": "% брака при поставке", "value": "", "status": "ok"},
             {"label": "Срок контроля", "value": "1–2 дня", "status": "ok"},
         ],
         description="Входной контроль качества и комплектности поступающих материальных ценностей. Документирование актами.",
         avg_days=2, position=10),
    dict(id="task_warehouse", label="Склад / выдача на сборку", dept_key="supply", x=LX + 800, y=288, w=170, h=76,
         type="task", issue="duplicate",
         docs=["Требование-накладная М-11", "Карточка складского учёта"],
         employees=["emp6"],
         kpis=[
             {"label": "Точность комплектации", "value": "", "status": "ok"},
             {"label": "Время выдачи", "value": "", "status": "ok"},
         ],
         description="Хранение и выдача материалов в производство. Дублирование учёта: в 1С и в Excel-таблицах склада.",
         avg_days=1, position=11),
    dict(id="task_montage", label="Монтаж оборудования в корпус", dept_key="assembly", x=LX + 320, y=418, w=180, h=76,
         type="task", issue="ok",
         docs=["Технологическая карта", "Схема размещения оборудования", "Инструкции производителей"],
         employees=["emp8", "emp9"],
         kpis=[
             {"label": "Выработка (шк./мес)", "value": "4–6 ед.", "status": "ok"},
             {"label": "Отклонение от плана", "value": "", "status": "ok"},
         ],
         description="Механический монтаж оборудования, автоматов, реле, DIN-рейки в корпус шкафа согласно схеме размещения.",
         avg_days=4, position=12),
    dict(id="task_wiring", label="Электромонтаж / кабельные работы", dept_key="assembly", x=LX + 570, y=418, w=180, h=76,
         type="task", issue="bottleneck",
         docs=["Схема Э3", "Кабельный журнал", "Маркировочные листы"],
         employees=["emp8", "emp10"],
         kpis=[
             {"label": "Трудоёмкость (ч/ед.)", "value": "32 ч", "status": "warn"},
             {"label": "Ошибки разводки", "value": "", "status": "warn"},
             {"label": "Переделки", "value": "", "status": "warn"},
         ],
         description="Прокладка кабелей, подключение по схемам. Узкое место: высокая трудоёмкость и ошибки из-за неактуальных схем.",
         avg_days=5, position=13),
    dict(id="task_test", label="Наладка и испытания", dept_key="assembly", x=LX + 820, y=418, w=150, h=76,
         type="task", issue="ok",
         docs=["Программа и методика испытаний", "Протокол испытаний", "Паспорт изделия"],
         employees=["emp11"],
         kpis=[
             {"label": "Процент с первого предъявления", "value": "", "status": "warn"},
             {"label": "Среднее время наладки", "value": "", "status": "ok"},
         ],
         description="Функциональные испытания шкафа, проверка автоматики, настройка параметров защит и управления.",
         avg_days=3, position=14),
    dict(id="task_otk", label="Контроль ОТК", dept_key="shipping", x=LX + 570, y=548, w=140, h=76,
         type="task", issue="ok",
         docs=["Акт приёмки ОТК", "Ведомость замечаний", "Паспорт изделия"],
         employees=["emp12"],
         kpis=[
             {"label": "% изделий с замечаниями", "value": "", "status": "warn"},
             {"label": "Срок устранения", "value": "1–3 дня", "status": "ok"},
         ],
         description="Финальный технический контроль качества готового изделия по требованиям договора и ГОСТам.",
         avg_days=2, position=15),
    dict(id="task_shipping", label="Упаковка и отгрузка", dept_key="shipping", x=LX + 800, y=548, w=170, h=76,
         type="task", issue="ok",
         docs=["Товарная накладная (ТОРГ-12)", "Упаковочный лист", "Акт сдачи-приёмки", "Инструкция по монтажу"],
         employees=["emp12", "emp13"],
         kpis=[
             {"label": "Своевременность отгрузки", "value": "", "status": "warn"},
             {"label": "Рекламации", "value": "", "status": "ok"},
         ],
         description="Упаковка изделия, оформление отгрузочных документов, передача заказчику или транспортной компании.",
         avg_days=2, position=16),
    dict(id="end", label="Завершено", dept_key="shipping", x=LX + 1040, y=568, w=36, h=36,
         type="event", issue="ok", docs=[], employees=[], kpis=[],
         description="Проект завершён. Шкаф управления передан заказчику.",
         avg_days=0, position=17),
]

EDGES = [
    dict(id="f1", from_node="start", to_node="task_tender", type="sequence", label=None, position=0),
    dict(id="f2", from_node="task_tender", to_node="gw_tender", type="sequence", label=None, position=1),
    dict(id="f3", from_node="gw_tender", to_node="task_contract", type="conditional", label="Да", position=2),
    dict(id="f4", from_node="task_contract", to_node="task_kickoff", type="sequence", label=None, position=3),
    dict(id="f5", from_node="task_kickoff", to_node="task_tz", type="message", label=None, position=4),
    dict(id="f6", from_node="task_tz", to_node="task_schema", type="sequence", label=None, position=5),
    dict(id="f7", from_node="task_schema", to_node="task_spec", type="sequence", label=None, position=6),
    dict(id="f8", from_node="task_spec", to_node="task_bom", type="sequence", label=None, position=7),
    dict(id="f9", from_node="task_bom", to_node="task_purchase", type="message", label=None, position=8),
    dict(id="f10", from_node="task_purchase", to_node="task_incoming", type="sequence", label=None, position=9),
    dict(id="f11", from_node="task_incoming", to_node="task_warehouse", type="sequence", label=None, position=10),
    dict(id="f12", from_node="task_warehouse", to_node="task_montage", type="message", label=None, position=11),
    dict(id="f13", from_node="task_bom", to_node="task_montage", type="message", label=None, position=12),
    dict(id="f14", from_node="task_montage", to_node="task_wiring", type="sequence", label=None, position=13),
    dict(id="f15", from_node="task_wiring", to_node="task_test", type="sequence", label=None, position=14),
    dict(id="f16", from_node="task_test", to_node="task_otk", type="message", label=None, position=15),
    dict(id="f17", from_node="task_otk", to_node="task_shipping", type="sequence", label=None, position=16),
    dict(id="f18", from_node="task_shipping", to_node="end", type="sequence", label=None, position=17),
]

PROBLEMS = [
    dict(id="bn1", title="Перегруз главного инженера", severity="crit", tasks=["task_tz"],
         description="Ильин Д.М. — единственный разработчик ТЗ. Задержка в ТЗ блокирует всю цепочку: схемы → BOM → закупки → сборку.",
         recommendation="Передать часть задач Савельеву К.Р. или нанять 2-го инженера-конструктора.", position=0),
    dict(id="bn2", title="Длинный срок поставки ТМЦ", severity="crit", tasks=["task_purchase"],
         description="Поставки, в т.ч. зарубежных компонентов, занимают существенную часть цикла. Возникает дефицит позиций.",
         recommendation="Ввести предварительное резервирование под типовые проекты, расширить базу локальных поставщиков.", position=1),
    dict(id="bn3", title="Высокая трудоёмкость электромонтажа", severity="warn", tasks=["task_wiring"],
         description="Электромонтаж — одна из самых трудоёмких операций, с переделками из-за расхождений между схемами и BOM.",
         recommendation="Внедрить PLM-систему для управления версиями схем; добавить цифровые маркировочные листы.", position=2),
    dict(id="bn4", title="Дублирование BOM в дизайне и снабжении", severity="warn", tasks=["task_spec", "task_warehouse"],
         description="BOM-лист формируется в КБ (Excel) и параллельно ведётся в 1С снабжением. Расхождения приводят к ошибкам закупки.",
         recommendation="Перейти на единую PDM/PLM систему (например, Lotsman или Teamcenter) как источник истины для BOM.", position=3),
    dict(id="bn5", title="Низкий % с первого предъявления ОТК", severity="warn", tasks=["task_test", "task_otk"],
         description="Часть изделий возвращается на доработку после ОТК, задерживая отгрузку.",
         recommendation="Внедрить промежуточный контроль после электромонтажа, ввести чек-лист самоконтроля монтажника.", position=4),
]
