"""add archive tables

Revision ID: 6045c7f945fb
Revises: 6bb361a0f4ae
Create Date: 2026-05-27 22:39:48.121458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6045c7f945fb'
down_revision: Union[str, None] = '6bb361a0f4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('related_entry_ids', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_entries_entry_type'), 'archive_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_archive_entries_is_deleted'), 'archive_entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_archive_entries_is_pinned'), 'archive_entries', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_archive_entries_occurred_at'), 'archive_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_archive_entries_project_id'), 'archive_entries', ['project_id'], unique=False)
    op.create_table('archive_constructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('construction_type', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('materials_used', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('documents_related', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='planned', nullable=False),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('tested_at', sa.Date(), nullable=True),
    sa.Column('accepted_at', sa.Date(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['archive_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_constructions_project_id'), 'archive_constructions', ['project_id'], unique=False)
    op.create_table('archive_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('used_in_constructions', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('attached_files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['archive_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_materials_project_id'), 'archive_materials', ['project_id'], unique=False)
    op.create_table('archive_search_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('construction_id', sa.UUID(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['construction_id'], ['archive_constructions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['archive_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_search_index_entry_id'), 'archive_search_index', ['entry_id'], unique=False)
    op.create_index(op.f('ix_archive_search_index_project_id'), 'archive_search_index', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archive_search_index_project_id'), table_name='archive_search_index')
    op.drop_index(op.f('ix_archive_search_index_entry_id'), table_name='archive_search_index')
    op.drop_table('archive_search_index')
    op.drop_index(op.f('ix_archive_materials_project_id'), table_name='archive_materials')
    op.drop_table('archive_materials')
    op.drop_index(op.f('ix_archive_constructions_project_id'), table_name='archive_constructions')
    op.drop_table('archive_constructions')
    op.drop_index(op.f('ix_archive_entries_project_id'), table_name='archive_entries')
    op.drop_index(op.f('ix_archive_entries_occurred_at'), table_name='archive_entries')
    op.drop_index(op.f('ix_archive_entries_is_pinned'), table_name='archive_entries')
    op.drop_index(op.f('ix_archive_entries_is_deleted'), table_name='archive_entries')
    op.drop_index(op.f('ix_archive_entries_entry_type'), table_name='archive_entries')
    op.drop_table('archive_entries')
    # ### end Alembic commands ###
