"""add gamification fks

Revision ID: 6b7a78f95758
Revises: de9b7d67b420
Create Date: 2026-05-28 00:17:48.392621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7a78f95758'
down_revision: Union[str, None] = 'de9b7d67b420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'combo_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'daily_quests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'engineer_metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gamification_badges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gamification_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'gamification_events', type_='foreignkey')
    op.drop_constraint(None, 'gamification_badges', type_='foreignkey')
    op.drop_constraint(None, 'engineer_metrics', type_='foreignkey')
    op.drop_constraint(None, 'daily_quests', type_='foreignkey')
    op.drop_constraint(None, 'combo_achievements', type_='foreignkey')
    # ### end Alembic commands ###
