"""make_archive_cross_db_compatible

Revision ID: 89eabce58d91
Revises: 
Create Date: 2026-05-31 16:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89eabce58d91'
down_revision: Union[str, None] = '582037ccf289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # archive_entries: tags ARRAY -> JSON (drop default first, then convert)
    op.execute("ALTER TABLE archive_entries ALTER COLUMN tags DROP DEFAULT")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN tags TYPE JSON USING to_jsonb(tags)")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN tags SET DEFAULT '[]'")
    
    # archive_entries: related_entry_ids ARRAY -> JSON
    op.execute("ALTER TABLE archive_entries ALTER COLUMN related_entry_ids DROP DEFAULT")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN related_entry_ids TYPE JSON USING to_jsonb(related_entry_ids)")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN related_entry_ids SET DEFAULT '[]'")
    
    # archive_entries: content_snapshot JSONB -> JSON
    op.execute("ALTER TABLE archive_entries ALTER COLUMN content_snapshot TYPE JSON USING content_snapshot::json")
    
    # archive_entries: attachments JSONB -> JSON
    op.execute("ALTER TABLE archive_entries ALTER COLUMN attachments DROP DEFAULT")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN attachments TYPE JSON USING attachments::json")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN attachments SET DEFAULT '[]'")
    
    # archive_materials: used_in_constructions ARRAY -> JSON
    op.execute("ALTER TABLE archive_materials ALTER COLUMN used_in_constructions DROP DEFAULT")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN used_in_constructions TYPE JSON USING to_jsonb(used_in_constructions)")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN used_in_constructions SET DEFAULT '[]'")
    
    # archive_materials: certificates JSONB -> JSON
    op.execute("ALTER TABLE archive_materials ALTER COLUMN certificates DROP DEFAULT")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN certificates TYPE JSON USING certificates::json")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN certificates SET DEFAULT '[]'")
    
    # archive_materials: attached_files JSONB -> JSON
    op.execute("ALTER TABLE archive_materials ALTER COLUMN attached_files DROP DEFAULT")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN attached_files TYPE JSON USING attached_files::json")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN attached_files SET DEFAULT '[]'")
    
    # archive_constructions: materials_used ARRAY -> JSON
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN materials_used DROP DEFAULT")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN materials_used TYPE JSON USING to_jsonb(materials_used)")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN materials_used SET DEFAULT '[]'")
    
    # archive_constructions: documents_related ARRAY -> JSON
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN documents_related DROP DEFAULT")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN documents_related TYPE JSON USING to_jsonb(documents_related)")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN documents_related SET DEFAULT '[]'")
    
    # archive_constructions: photos JSONB -> JSON
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN photos DROP DEFAULT")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN photos TYPE JSON USING photos::json")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN photos SET DEFAULT '[]'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # archive_entries: JSON -> ARRAY
    op.execute("ALTER TABLE archive_entries ALTER COLUMN tags DROP DEFAULT")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN tags TYPE VARCHAR[] USING ARRAY(SELECT jsonb_array_elements_text(tags::jsonb))")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN tags SET DEFAULT '{}'")
    
    op.execute("ALTER TABLE archive_entries ALTER COLUMN related_entry_ids DROP DEFAULT")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN related_entry_ids TYPE UUID[] USING ARRAY(SELECT jsonb_array_elements_text(related_entry_ids::jsonb)::uuid)")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN related_entry_ids SET DEFAULT '{}'")
    
    op.execute("ALTER TABLE archive_entries ALTER COLUMN content_snapshot TYPE JSONB USING content_snapshot::jsonb")
    
    op.execute("ALTER TABLE archive_entries ALTER COLUMN attachments DROP DEFAULT")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN attachments TYPE JSONB USING attachments::jsonb")
    op.execute("ALTER TABLE archive_entries ALTER COLUMN attachments SET DEFAULT '[]'")
    
    # archive_materials
    op.execute("ALTER TABLE archive_materials ALTER COLUMN used_in_constructions DROP DEFAULT")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN used_in_constructions TYPE UUID[] USING ARRAY(SELECT jsonb_array_elements_text(used_in_constructions::jsonb)::uuid)")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN used_in_constructions SET DEFAULT '{}'")
    
    op.execute("ALTER TABLE archive_materials ALTER COLUMN certificates DROP DEFAULT")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN certificates TYPE JSONB USING certificates::jsonb")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN certificates SET DEFAULT '[]'")
    
    op.execute("ALTER TABLE archive_materials ALTER COLUMN attached_files DROP DEFAULT")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN attached_files TYPE JSONB USING attached_files::jsonb")
    op.execute("ALTER TABLE archive_materials ALTER COLUMN attached_files SET DEFAULT '[]'")
    
    # archive_constructions
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN materials_used DROP DEFAULT")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN materials_used TYPE UUID[] USING ARRAY(SELECT jsonb_array_elements_text(materials_used::jsonb)::uuid)")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN materials_used SET DEFAULT '{}'")
    
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN documents_related DROP DEFAULT")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN documents_related TYPE UUID[] USING ARRAY(SELECT jsonb_array_elements_text(documents_related::jsonb)::uuid)")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN documents_related SET DEFAULT '{}'")
    
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN photos DROP DEFAULT")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN photos TYPE JSONB USING photos::jsonb")
    op.execute("ALTER TABLE archive_constructions ALTER COLUMN photos SET DEFAULT '[]'")
    
    # ### end Alembic commands ###
