"""add_task_id_to_time_sessions

Revision ID: a2297f006ed5
Revises: 582037ccf289
Create Date: 2026-05-28 19:52:18.268964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2297f006ed5'
down_revision: Union[str, None] = '582037ccf289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_sessions', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'time_sessions', 'tasks', ['task_id'], ['id'])
    op.create_index('ix_timesession_task_started', 'time_sessions', ['task_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timesession_task_started', table_name='time_sessions')
    op.drop_constraint(None, 'time_sessions', type_='foreignkey')
    op.drop_column('time_sessions', 'task_id')
    # ### end Alembic commands ###
