"""initial_schema

Revision ID: bb738b9eb80a
Revises: 
Create Date: 2026-05-06 13:14:22.825471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb738b9eb80a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combo_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('combo_type', sa.String(length=100), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_achievements_user_id'), 'combo_achievements', ['user_id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quests_quest_type'), 'daily_quests', ['quest_type'], unique=False)
    op.create_index(op.f('ix_daily_quests_user_id'), 'daily_quests', ['user_id'], unique=False)
    op.create_table('engineer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('documents_closed', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gamification_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_gamification_badges_user_id'), 'gamification_badges', ['user_id'], unique=False)
    op.create_table('gamification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('xp_delta', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_key', sa.String(length=255), nullable=True),
    sa.Column('ref_doc_id', sa.Integer(), nullable=True),
    sa.Column('ref_task_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_events_user_id'), 'gamification_events', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('remark_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('standard_template_id', sa.String(length=50), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('planned_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('volume_unit', sa.String(length=20), nullable=True),
    sa.Column('complexity', sa.String(length=20), nullable=False),
    sa.Column('standards', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('nmc', sa.Float(), nullable=True),
    sa.Column('our_price', sa.Float(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('auction_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loss_reason', sa.String(length=255), nullable=True),
    sa.Column('calculated_hours', sa.Float(), nullable=True),
    sa.Column('calculated_cost', sa.Float(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('team_composition', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_centers_code'), 'work_centers', ['code'], unique=True)
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_table('employee_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_hours', sa.Float(), nullable=False),
    sa.Column('actual_hours', sa.Float(), nullable=False),
    sa.Column('available_hours', sa.Float(), nullable=False),
    sa.Column('load_percentage', sa.Float(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_project_id'), 'routes', ['project_id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_document_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('target_document_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_route_id'), 'operations', ['route_id'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_source_id', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('diff_before', sa.JSON(), nullable=True),
    sa.Column('diff_after', sa.JSON(), nullable=True),
    sa.Column('affected_variables', sa.JSON(), nullable=True),
    sa.Column('affected_documents', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rev_document_created', 'revisions', ['document_id', 'created_at'], unique=False)
    op.create_table('time_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('active_time', sa.Integer(), nullable=False),
    sa.Column('idle_time', sa.Integer(), nullable=False),
    sa.Column('breaks', sa.JSON(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('blocks_modified', sa.JSON(), nullable=True),
    sa.Column('variables_changed', sa.JSON(), nullable=True),
    sa.Column('revisions_created', sa.Integer(), nullable=False),
    sa.Column('remarks_resolved', sa.Integer(), nullable=False),
    sa.Column('remarks_created', sa.Integer(), nullable=False),
    sa.Column('approvals_given', sa.Integer(), nullable=False),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('complexity_index', sa.Float(), nullable=True),
    sa.Column('normalized_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_sessions_document_id'), 'time_sessions', ['document_id'], unique=False)
    op.create_index(op.f('ix_time_sessions_project_id'), 'time_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_sessions_started_at'), 'time_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_time_sessions_user_id'), 'time_sessions', ['user_id'], unique=False)
    op.create_index('ix_timesession_project_started', 'time_sessions', ['project_id', 'started_at'], unique=False)
    op.create_index('ix_timesession_user_project', 'time_sessions', ['user_id', 'project_id'], unique=False)
    op.create_index('ix_timesession_user_started', 'time_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_rule', sa.String(length=255), nullable=True),
    sa.Column('is_computed', sa.Boolean(), nullable=False),
    sa.Column('computed_expression', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_var_project_key', 'variables', ['project_id', 'key'], unique=False)
    op.create_index('ix_var_scope_key', 'variables', ['scope', 'key'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_revision', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', 'PAUSED', 'CANCELLED', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('launch_comment', sa.Text(), nullable=True),
    sa.Column('document_changed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('table_data', sa.JSON(), nullable=True),
    sa.Column('stamp_entries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('remark_type', sa.String(length=50), nullable=False),
    sa.Column('source_author_id', sa.Integer(), nullable=True),
    sa.Column('source_organization', sa.String(length=255), nullable=True),
    sa.Column('source_department', sa.String(length=100), nullable=True),
    sa.Column('source_role', sa.String(length=100), nullable=True),
    sa.Column('target_page', sa.Integer(), nullable=True),
    sa.Column('target_coordinates', sa.JSON(), nullable=True),
    sa.Column('target_element_id', sa.String(length=100), nullable=True),
    sa.Column('target_text_selection', sa.Text(), nullable=True),
    sa.Column('target_screenshot', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('workflow_history', sa.JSON(), nullable=True),
    sa.Column('resolution_action', sa.String(length=50), nullable=True),
    sa.Column('resolution_revision_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confirmed_by_customer', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['resolution_revision_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['source_author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remark_document_status', 'document_remarks', ['document_id', 'status'], unique=False)
    op.create_index('ix_remark_document_status_severity', 'document_remarks', ['document_id', 'status', 'severity'], unique=False)
    op.create_index('ix_remark_severity_created', 'document_remarks', ['severity', 'created_at'], unique=False)
    op.create_table('operation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_assignments_operation_id'), 'operation_assignments', ['operation_id'], unique=False)
    op.create_index(op.f('ix_operation_assignments_user_id'), 'operation_assignments', ['user_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('PRODUCTION', 'DOCUMENT', 'APPROVAL', 'REVIEW', 'ISSUE', 'PLANNING', 'MEETING', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'ON_HOLD', 'DONE', 'CANCELLED', 'REVIEW', 'APPROVAL', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('work_center_id', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('actual_hours', sa.Float(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date', 'status'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('idx_tasks_type_status', 'tasks', ['type', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_document_id'), 'tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_tasks_operation_id'), 'tasks', ['operation_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_route_id'), 'tasks', ['route_id'], unique=False)
    op.create_table('variable_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('from_value', sa.Text(), nullable=True),
    sa.Column('to_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('assignment_type', sa.Enum('SEQUENTIAL', 'PARALLEL', 'ANY_OF', name='assignmenttype'), nullable=False),
    sa.Column('approval_type', sa.Enum('VIEW_ONLY', 'APPROVE', 'APPROVE_WITH_COMMENTS', name='approvaltype'), nullable=False),
    sa.Column('deadline_hours', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'DELEGATED', 'SKIPPED', name='workflowstepstatus'), nullable=False),
    sa.Column('auto_transition', sa.JSON(), nullable=True),
    sa.Column('is_delegated', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('workflow_step_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_ref', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('related_remark_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.Column('updated_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['remarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_step_assignees',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'user_id')
    )
    op.create_table('remark_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remark_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remark_tag_links',
    sa.Column('remark_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['remark_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('remark_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remark_tag_links')
    op.drop_table('remark_comments')
    op.drop_table('workflow_step_assignees')
    op.drop_table('workflow_comments')
    op.drop_table('workflow_audit_log')
    op.drop_table('remarks')
    op.drop_table('approval_stages')
    op.drop_table('workflow_steps')
    op.drop_table('variable_revisions')
    op.drop_index(op.f('ix_tasks_route_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_operation_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_document_id'), table_name='tasks')
    op.drop_index('idx_tasks_type_status', table_name='tasks')
    op.drop_index('idx_tasks_project_status', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_assignee_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('sections')
    op.drop_index(op.f('ix_operation_assignments_user_id'), table_name='operation_assignments')
    op.drop_index(op.f('ix_operation_assignments_operation_id'), table_name='operation_assignments')
    op.drop_table('operation_assignments')
    op.drop_index('ix_remark_severity_created', table_name='document_remarks')
    op.drop_index('ix_remark_document_status_severity', table_name='document_remarks')
    op.drop_index('ix_remark_document_status', table_name='document_remarks')
    op.drop_table('document_remarks')
    op.drop_table('change_sheets')
    op.drop_table('approval_workflows')
    op.drop_table('workflow_instances')
    op.drop_index('ix_var_scope_key', table_name='variables')
    op.drop_index('ix_var_project_key', table_name='variables')
    op.drop_table('variables')
    op.drop_index('ix_timesession_user_started', table_name='time_sessions')
    op.drop_index('ix_timesession_user_project', table_name='time_sessions')
    op.drop_index('ix_timesession_project_started', table_name='time_sessions')
    op.drop_index(op.f('ix_time_sessions_user_id'), table_name='time_sessions')
    op.drop_index(op.f('ix_time_sessions_started_at'), table_name='time_sessions')
    op.drop_index(op.f('ix_time_sessions_project_id'), table_name='time_sessions')
    op.drop_index(op.f('ix_time_sessions_document_id'), table_name='time_sessions')
    op.drop_table('time_sessions')
    op.drop_index('ix_rev_document_created', table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_operations_route_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_table('kits')
    op.drop_table('document_dependencies')
    op.drop_table('tender_document_previews')
    op.drop_table('stages')
    op.drop_index(op.f('ix_routes_project_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('employee_loads')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_index('ix_documents_document_type', table_name='documents')
    op.drop_table('documents')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_work_centers_code'), table_name='work_centers')
    op.drop_table('work_centers')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('remark_tags')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_gamification_events_user_id'), table_name='gamification_events')
    op.drop_table('gamification_events')
    op.drop_index(op.f('ix_gamification_badges_user_id'), table_name='gamification_badges')
    op.drop_table('gamification_badges')
    op.drop_table('engineer_metrics')
    op.drop_index(op.f('ix_daily_quests_user_id'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_quest_type'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_combo_achievements_user_id'), table_name='combo_achievements')
    op.drop_table('combo_achievements')
    # ### end Alembic commands ###
