"""init

Revision ID: de47c64cbf89
Revises: 
Create Date: 2026-04-21 14:37:04.593973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de47c64cbf89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_time_logs_project_date_desc', table_name='time_logs')
    op.drop_index('idx_time_logs_project_day', table_name='time_logs')
    op.drop_index('idx_time_logs_user_day', table_name='time_logs')
    op.drop_index('idx_time_logs_user_project_date', table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_status_manager', table_name='projects')
    op.drop_table('projects')
    op.drop_table('engineer_metrics')
    op.drop_index('idx_remarks_assignee', table_name='remarks')
    op.drop_index('idx_remarks_project', table_name='remarks')
    op.drop_index('idx_remarks_project_id', table_name='remarks')
    op.drop_index('idx_remarks_project_status', table_name='remarks')
    op.drop_index('idx_remarks_status', table_name='remarks')
    op.drop_index('idx_remarks_unresolved', table_name='remarks', postgresql_where="(status <> 'resolved'::text)")
    op.drop_table('remarks')
    op.drop_index('idx_gamification_events_created_at', table_name='gamification_events')
    op.drop_index('idx_gamification_events_user', table_name='gamification_events')
    op.drop_index('idx_gamification_events_user_date', table_name='gamification_events')
    op.drop_index('idx_gamification_events_user_points', table_name='gamification_events', postgresql_include=['points_delta'])
    op.drop_index('idx_gamification_events_user_type', table_name='gamification_events')
    op.drop_table('gamification_events')
    op.drop_index('idx_badges_user_awarded', table_name='gamification_badges')
    op.drop_index('idx_gamification_badges_user', table_name='gamification_badges')
    op.drop_table('gamification_badges')
    op.drop_index('idx_daily_quests_type', table_name='daily_quests')
    op.drop_index('idx_daily_quests_user_date', table_name='daily_quests')
    op.drop_index('idx_daily_quests_user_date_completed', table_name='daily_quests', postgresql_where='(is_completed = true)')
    op.drop_table('daily_quests')
    op.drop_index('idx_remark_responses_remark', table_name='remark_responses')
    op.drop_table('remark_responses')
    op.drop_index('idx_documents_code', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_index('idx_documents_project_id', table_name='documents')
    op.drop_index('idx_documents_project_status', table_name='documents')
    op.drop_index('idx_documents_project_status_created', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_title_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('uq_documents_project_code', table_name='documents')
    op.drop_table('documents')
    op.drop_table('work_schedules')
    op.drop_index('uq_mdr_project_docnum', table_name='mdr_entries')
    op.drop_table('mdr_entries')
    op.drop_index('idx_uploaded_files_file_id', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('idx_combo_achievements_user_active', table_name='combo_achievements')
    op.drop_index('idx_combo_user_active', table_name='combo_achievements')
    op.drop_table('combo_achievements')
    op.drop_index('uq_vdr_project_docnum', table_name='vdr_entries')
    op.drop_table('vdr_entries')
    op.drop_index('idx_tender_documents_tender', table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index('idx_document_revisions_document', table_name='document_revisions')
    op.drop_index('idx_revisions_document_id', table_name='document_revisions')
    op.drop_index('idx_revisions_status', table_name='document_revisions')
    op.drop_index('uq_document_revision_idx', table_name='document_revisions')
    op.drop_index('uq_document_revision_version', table_name='document_revisions')
    op.drop_table('document_revisions')
    op.drop_index('idx_notifications_unread', table_name='notifications')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_user_created', table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_table('notifications')
    op.drop_index('idx_project_metrics_calculated', table_name='project_metrics')
    op.drop_index('idx_project_metrics_project', table_name='project_metrics')
    op.drop_index('idx_project_metrics_project_latest', table_name='project_metrics')
    op.drop_table('project_metrics')
    op.drop_index('idx_planned_tasks_assigned_to', table_name='planned_tasks')
    op.drop_index('idx_planned_tasks_project', table_name='planned_tasks')
    op.drop_index('idx_tasks_assigned_to', table_name='planned_tasks')
    op.drop_index('idx_tasks_assignee_status_date', table_name='planned_tasks')
    op.drop_index('idx_tasks_dates', table_name='planned_tasks')
    op.drop_index('idx_tasks_overdue', table_name='planned_tasks', postgresql_where="(status <> ALL (ARRAY['completed'::text, 'cancelled'::text]))")
    op.drop_index('idx_tasks_project_id', table_name='planned_tasks')
    op.drop_index('idx_tasks_project_revision', table_name='planned_tasks')
    op.drop_index('idx_tasks_project_status_deadline', table_name='planned_tasks')
    op.drop_index('idx_tasks_status', table_name='planned_tasks')
    op.drop_table('planned_tasks')
    op.drop_index('idx_tenders_created_at', table_name='tenders')
    op.drop_index('idx_tenders_status', table_name='tenders')
    op.drop_index('idx_tenders_status_created', table_name='tenders')
    op.drop_table('tenders')
    op.drop_index('idx_deps_predecessor', table_name='task_dependencies')
    op.drop_index('idx_deps_project_id', table_name='task_dependencies')
    op.drop_index('idx_deps_successor', table_name='task_dependencies')
    op.drop_index('idx_task_dependencies_project', table_name='task_dependencies')
    op.drop_index('idx_task_dependencies_successor', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'login')
    op.drop_column('users', 'username')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'rank')
    op.drop_column('users', 'discipline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discipline', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rank', sa.TEXT(), server_default=sa.text("'junior'::text"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.TEXT(), server_default=sa.text("'engineer'::text"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('login', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    op.create_table('task_dependencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predecessor_task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successor_task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_type', sa.TEXT(), server_default=sa.text("'FS'::text"), autoincrement=False, nullable=False),
    sa.Column('lag_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['planned_tasks.id'], name='task_dependencies_predecessor_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='task_dependencies_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_task_id'], ['planned_tasks.id'], name='task_dependencies_successor_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_dependencies_pkey')
    )
    op.create_index('idx_task_dependencies_successor', 'task_dependencies', ['successor_task_id'], unique=False)
    op.create_index('idx_task_dependencies_project', 'task_dependencies', ['project_id'], unique=False)
    op.create_index('idx_deps_successor', 'task_dependencies', ['successor_task_id'], unique=False)
    op.create_index('idx_deps_project_id', 'task_dependencies', ['project_id'], unique=False)
    op.create_index('idx_deps_predecessor', 'task_dependencies', ['predecessor_task_id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tenders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('customer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('deadline_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'::text"), autoincrement=False, nullable=False),
    sa.Column('vdr_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('otk_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('logistics_complexity', sa.TEXT(), server_default=sa.text("'normal'::text"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('required_disciplines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('team_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_review_rounds', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('expected_remark_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('assessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('assessment_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='tenders_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='tenders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_tenders_status_created', 'tenders', ['status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_tenders_status', 'tenders', ['status'], unique=False)
    op.create_index('idx_tenders_created_at', 'tenders', ['created_at'], unique=False)
    op.create_table('planned_tasks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planned_tasks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revision_index', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.TEXT(), server_default=sa.text("'engineering'::text"), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_days_planned', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('work_hours_planned', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('start_date_planned', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date_planned', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('start_date_actual', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date_actual', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('percent_complete', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'not_started'::text"), autoincrement=False, nullable=False),
    sa.Column('es', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ef', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lf', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='planned_tasks_assigned_to_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='planned_tasks_document_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='planned_tasks_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['document_revisions.id'], name='planned_tasks_revision_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='planned_tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_tasks_status', 'planned_tasks', ['status'], unique=False)
    op.create_index('idx_tasks_project_status_deadline', 'planned_tasks', ['project_id', 'status', 'end_date_planned'], unique=False)
    op.create_index('idx_tasks_project_revision', 'planned_tasks', ['project_id', 'revision_id'], unique=False)
    op.create_index('idx_tasks_project_id', 'planned_tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_overdue', 'planned_tasks', ['status', 'end_date_planned'], unique=False, postgresql_where="(status <> ALL (ARRAY['completed'::text, 'cancelled'::text]))")
    op.create_index('idx_tasks_dates', 'planned_tasks', ['start_date_planned', 'end_date_planned'], unique=False)
    op.create_index('idx_tasks_assignee_status_date', 'planned_tasks', ['assigned_to', 'status', 'start_date_planned'], unique=False)
    op.create_index('idx_tasks_assigned_to', 'planned_tasks', ['assigned_to'], unique=False)
    op.create_index('idx_planned_tasks_project', 'planned_tasks', ['project_id'], unique=False)
    op.create_index('idx_planned_tasks_assigned_to', 'planned_tasks', ['assigned_to'], unique=False)
    op.create_table('project_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('in_progress_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('not_started_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spi', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('cpi', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('critical_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overdue_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_planned_hours', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('completed_hours', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_metrics_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_metrics_pkey')
    )
    op.create_index('idx_project_metrics_project_latest', 'project_metrics', ['project_id', 'calculated_at'], unique=False)
    op.create_index('idx_project_metrics_project', 'project_metrics', ['project_id'], unique=False)
    op.create_index('idx_project_metrics_calculated', 'project_metrics', ['calculated_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_notifications_user_created', 'notifications', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('document_revisions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('document_revisions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision_index', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('revision_letter', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('revision_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('change_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('uploaded_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validation_profile', sa.TEXT(), server_default=sa.text("'ESKD'::text"), autoincrement=False, nullable=True),
    sa.Column('validation_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_errors', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='document_revisions_approved_by_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='document_revisions_created_by_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_revisions_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], name='fk_document_revisions_uploaded_file'),
    sa.PrimaryKeyConstraint('id', name='document_revisions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('uq_document_revision_version', 'document_revisions', ['document_id', 'version_number'], unique=True)
    op.create_index('uq_document_revision_idx', 'document_revisions', ['document_id', 'revision_letter', 'revision_number'], unique=True)
    op.create_index('idx_revisions_status', 'document_revisions', ['status'], unique=False)
    op.create_index('idx_revisions_document_id', 'document_revisions', ['document_id'], unique=False)
    op.create_index('idx_document_revisions_document', 'document_revisions', ['document_id'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours_per_doc', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name='tender_documents_tender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tender_documents_pkey')
    )
    op.create_index('idx_tender_documents_tender', 'tender_documents', ['tender_id'], unique=False)
    op.create_table('vdr_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responsible_contractor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latest_revision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latest_upload_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_auto_filled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='vdr_entries_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vdr_entries_pkey')
    )
    op.create_index('uq_vdr_project_docnum', 'vdr_entries', ['project_id', 'doc_number'], unique=True)
    op.create_table('combo_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('combo_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_count', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('multiplier', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='combo_achievements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='combo_achievements_pkey')
    )
    op.create_index('idx_combo_user_active', 'combo_achievements', ['user_id', 'combo_type', 'expires_at', 'is_active'], unique=False)
    op.create_index('idx_combo_achievements_user_active', 'combo_achievements', ['user_id', 'is_active'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('uploaded_files_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stored_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='uploaded_files_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='uploaded_files_pkey'),
    sa.UniqueConstraint('file_id', name='uploaded_files_file_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_uploaded_files_file_id', 'uploaded_files', ['file_id'], unique=False)
    op.create_table('mdr_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revision_current', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('planned_issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('actual_issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_auto_filled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='mdr_entries_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mdr_entries_pkey')
    )
    op.create_index('uq_mdr_project_docnum', 'mdr_entries', ['project_id', 'doc_number'], unique=True)
    op.create_table('work_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('work_days', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[0,1,2,3,4]'::json"), autoincrement=False, nullable=False),
    sa.Column('start_time_hours', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('8.5'), autoincrement=False, nullable=False),
    sa.Column('end_time_hours', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('17.5'), autoincrement=False, nullable=False),
    sa.Column('lunch_duration_hours', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='work_schedules_pkey'),
    sa.UniqueConstraint('name', name='work_schedules_name_key')
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('documents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'in_work'::text"), autoincrement=False, nullable=False),
    sa.Column('current_revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='documents_created_by_fkey'),
    sa.ForeignKeyConstraint(['current_revision_id'], ['document_revisions.id'], name='fk_documents_current_revision'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='documents_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('uq_documents_project_code', 'documents', ['project_id', 'code'], unique=True)
    op.create_index('idx_documents_title_gin', 'documents', [sa.text("to_tsvector('russian'::regconfig, title)")], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_project_status_created', 'documents', ['project_id', 'status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_documents_project_status', 'documents', ['project_id', 'status'], unique=False)
    op.create_index('idx_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_index('idx_documents_created_at', 'documents', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_documents_code', 'documents', ['code'], unique=False)
    op.create_table('remark_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('remark_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='remark_responses_author_id_fkey'),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], name='remark_responses_remark_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='remark_responses_pkey')
    )
    op.create_index('idx_remark_responses_remark', 'remark_responses', ['remark_id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quest_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('reward_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_xp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_quests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_quests_pkey')
    )
    op.create_index('idx_daily_quests_user_date_completed', 'daily_quests', ['user_id', 'date', 'is_completed'], unique=False, postgresql_where='(is_completed = true)')
    op.create_index('idx_daily_quests_user_date', 'daily_quests', ['user_id', 'date'], unique=False)
    op.create_index('idx_daily_quests_type', 'daily_quests', ['quest_type'], unique=False)
    op.create_table('gamification_badges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gamification_badges_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gamification_badges_pkey'),
    sa.UniqueConstraint('user_id', 'badge_id', name='gamification_badges_user_id_badge_id_key')
    )
    op.create_index('idx_gamification_badges_user', 'gamification_badges', ['user_id'], unique=False)
    op.create_index('idx_badges_user_awarded', 'gamification_badges', ['user_id', sa.text('awarded_at DESC')], unique=False)
    op.create_table('gamification_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('points_delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('xp_delta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('action_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ref_doc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ref_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='gamification_events_project_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ref_doc_id'], ['documents.id'], name='gamification_events_ref_doc_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ref_task_id'], ['planned_tasks.id'], name='gamification_events_ref_task_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gamification_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gamification_events_pkey')
    )
    op.create_index('idx_gamification_events_user_type', 'gamification_events', ['user_id', 'event_type'], unique=False)
    op.create_index('idx_gamification_events_user_points', 'gamification_events', ['user_id'], unique=False, postgresql_include=['points_delta'])
    op.create_index('idx_gamification_events_user_date', 'gamification_events', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_gamification_events_user', 'gamification_events', ['user_id'], unique=False)
    op.create_index('idx_gamification_events_created_at', 'gamification_events', [sa.text('created_at DESC')], unique=False)
    op.create_table('remarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'internal'::text"), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=False),
    sa.Column('resolution_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='remarks_assignee_id_fkey'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='remarks_author_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='remarks_document_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='remarks_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['document_revisions.id'], name='remarks_revision_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='remarks_pkey')
    )
    op.create_index('idx_remarks_unresolved', 'remarks', ['project_id', 'status'], unique=False, postgresql_where="(status <> 'resolved'::text)")
    op.create_index('idx_remarks_status', 'remarks', ['project_id', 'status'], unique=False)
    op.create_index('idx_remarks_project_status', 'remarks', ['project_id', 'status'], unique=False)
    op.create_index('idx_remarks_project_id', 'remarks', ['project_id'], unique=False)
    op.create_index('idx_remarks_project', 'remarks', ['project_id'], unique=False)
    op.create_index('idx_remarks_assignee', 'remarks', ['assignee_id'], unique=False)
    op.create_table('engineer_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rank', sa.TEXT(), server_default=sa.text("'junior'::text"), autoincrement=False, nullable=False),
    sa.Column('tasks_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('documents_closed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='engineer_metrics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='engineer_metrics_pkey'),
    sa.UniqueConstraint('user_id', name='engineer_metrics_user_id_key')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('customer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date_planned', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date_forecast', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date_actual', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vdr_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('otk_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('crs_deadline_days', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('logistics_delivery_weeks', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=False),
    sa.Column('logistics_complexity', sa.TEXT(), server_default=sa.text("'normal'::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='projects_manager_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    sa.UniqueConstraint('code', name='projects_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_projects_status_manager', 'projects', ['status', 'manager_id'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_table('time_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='time_logs_document_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='time_logs_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['planned_tasks.id'], name='time_logs_task_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='time_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_logs_pkey')
    )
    op.create_index('idx_time_logs_user_project_date', 'time_logs', ['user_id', 'project_id', sa.text('day DESC')], unique=False)
    op.create_index('idx_time_logs_user_day', 'time_logs', ['user_id', 'day'], unique=False)
    op.create_index('idx_time_logs_project_day', 'time_logs', ['project_id', 'day'], unique=False)
    op.create_index('idx_time_logs_project_date_desc', 'time_logs', ['project_id', sa.text('day DESC')], unique=False)
    # ### end Alembic commands ###
