"""add project_id to tenders

Revision ID: de9b7d67b420
Revises: 81b7ada1748c
Create Date: 2026-05-27 23:58:50.749927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9b7d67b420'
down_revision: Union[str, None] = '81b7ada1748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tasks_due_date_status', 'tasks', ['due_date', 'status'], unique=False)
    op.add_column('tenders', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenders', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenders', type_='foreignkey')
    op.drop_column('tenders', 'project_id')
    op.drop_index('idx_tasks_due_date_status', table_name='tasks')
    # ### end Alembic commands ###
