"""Add document schedule fields

Revision ID: deb26813c38d
Revises: 76a4efa5dc26
Create Date: 2026-04-22 15:28:07.593060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb26813c38d'
down_revision: Union[str, None] = '76a4efa5dc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('duration_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'duration_hours')
    op.drop_column('documents', 'actual_end')
    op.drop_column('documents', 'actual_start')
    op.drop_column('documents', 'planned_end')
    op.drop_column('documents', 'planned_start')
    # ### end Alembic commands ###
